import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import { GoalList } from "../components/GoalList";
import { AddGoal } from "../components/AddGoal";
import { Card } from "../components/Card";
import { Input } from "../components/Input";
import { Button } from "../components/Button";
import Image from "next/image";
import { SignInForm } from "../components/SignInForm";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const { data: goals } = trpc.goal.getAll.useQuery();
  const utils = trpc.useContext();

  const handleAdd = () => {
    utils.goal.getAll.invalidate();
  };
  return (
    <>
      <Head>
        <title>Power of habits</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full items-center justify-center">
        <SignInForm />
      </main>

      {session?.user && <AddGoal onAdd={handleAdd}></AddGoal>}
      {session?.user && <GoalList goals={goals}></GoalList>}
    </>
  );
};

export default Home;
