import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import { SignInForm } from "../components/SignInForm";
import Goals from "../layouts/Goals";
import Header from "../components/Header";

const Home: NextPage = () => {
  const { data: session } = useSession();

  let content;
  if (!session?.user) {
    content = <SignInForm />;
  } else {
    content = <Goals />;
  }

  return (
    <>
      <Head>
        <title>Power of habits</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session?.user && <Header />}

      <main className="flex h-full items-center justify-center">{content}</main>
    </>
  );
};

export default Home;
