import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import Goals from "../layouts/Goals";
import Login from "../layouts/Login";

const Home: NextPage = () => {
  const { data: session } = useSession();

  let content;
  if (!session?.user) {
    content = <Login />;
  } else {
    content = <Goals />;
  }

  return (
    <>
      <Head>
        <title>Power of habits</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {content}
    </>
  );
};

export default Home;
